name: Run Dataset Category Management

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * 1'  # Run every Monday at 00:00 UTC

env:
  GBIF_EMAIL: ${{ secrets.GBIF_EMAIL }}
  GBIF_USER: ${{ secrets.GBIF_USER }}
  GBIF_PWD: ${{ secrets.GBIF_PWD }}
  GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  run-project:
    runs-on: ubuntu-latest
    steps:
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libcurl4-openssl-dev

      - name: Install shyaml
        run: |
          pip install shyaml

      - name: Check GitHub CLI version
        run: gh --version
          
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up R
        uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.3.1'

      - name: Cache R packages
        uses: actions/cache@v4
        with:
          path: ~/.local/share/R
          key: ${{ runner.os }}-r-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-r-

      - name: Cache pak
        uses: actions/cache@v4
        with:
          path: ~/.cache/R/pak
          key: ${{ runner.os }}-pak-${{ hashFiles('**/*.lock') }}
          restore-keys: |
            ${{ runner.os }}-pak-

      - name: Install R dependencies
        run: |
          Rscript -e "install.packages('pak', repos='https://cloud.r-project.org/')"
          Rscript -e "pak::pkg_install(c('tidyr','httr','yaml','data.table','dplyr','rgbif','tibble','readr','stringr','purrr'))"
          Rscript -e "pak::pkg_install('jhnwllr/gbifmt')"

      - name: Run shell scripts
        run: |
          bash run.sh

      - name: Check if files were updated
        run: |
          head candidate-tsv/eDNA.tsv
          echo "Number of lines in eDNA.tsv:"
          wc -l candidate-tsv/eDNA.tsv
          echo "Number of lines in issue_log.txt:"
          head shell/issue_log.txt
          wc -l shell/issue_log.txt

        
      - name: Commit & push changes
        uses: stefanzweifel/git-auto-commit-action@v5
